pulse.rules = [
    {
        matches = [
            { application.name = "Firefox" }
            { application.name = "Chromium" }
            { application.name = "Plex" }
        ]
        actions = {
            update-props = {
                target.object  = "loopback-mediaplayer"
                audio.channels = 2
                audio.position = [ FL FR ]
            }
        }
    }
]
